name: Rolling Build Main
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '13 4 * * *'

jobs:
  jazzy_binary_main:
    uses: ./.github/workflows/reusable_ici.yml
    with:
      ros_distro: rolling
      ros_repo: main
      upstream_workspace: 'repos.list'
      ref_for_scheduled_build: main
      before_install_upstream_dependencies: 'sudo apt install -y libboost-regex-dev'
